### ISSUE TITLE
ModuleNotFoundError: No module named 'dpdb.io'

### ISSUE THREAD

**Issue by vuphan314** [vuphan314/nesthdb#1]
I made this clone of [nestHDB](https://tinyurl.com/nesthdb) from its SAT-2021 [paper](https://link.springer.com/chapter/10.1007/978-3-030-51825-7_25).

I got an error with the main script:
```
$ ./nesthdb.py 
Traceback (most recent call last):
  File "./nesthdb.py", line 10, in <module>
    from common import *
  File "/home/vhp1/code/nesthdb/common.py", line 7, in <module>
    from dpdb.db import DEBUG_SQL
  File "/home/vhp1/code/nesthdb/dpdb/__init__.py", line 1, in <module>
    from .io import * 
ModuleNotFoundError: No module named 'dpdb.io'
```

The offending line:
https://github.com/vuphan314/nesthdb/blob/0c138b3e23721c901c79a6e1444db7a38d848fd3/dpdb/__init__.py#L1

**Comment by vuphan314** [comment]
I can now run `nesthdb` on my laptop:

https://github.com/hmarkus/dp_on_dbs/pull/9
